
from typing import TypedDict, Annotated, Optional, Dict, Any, List, Literal
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from datetime import datetime

class QueryResults(TypedDict):
    """
    Serializable query results from Athena.
    This format ensures results can be stored in checkpointer.
    """
    columns: List[str]
    data: List[List[Any]]
    dtypes: Optional[Dict[str, str]]
    row_count: Optional[int]
    execution_time: Optional[float]

class ChartConfig(TypedDict):
    """
    Chart configuration for UI rendering.
    Generated by LLM based on query results.
    """
    chart_type: Literal['pie', 'bar', 'bar_horizontal', 'line', 'scatter', 'area', 'table']
    title: str
    columns: List[str]
    data: List[List[Any]]
    metadata: Optional[Dict[str, Any]]  # Additional chart options

class ChatState(TypedDict):
    """
    Main application state for LangGraph workflow.
    
    Flow:
    1. User message arrives
    2. classify_query_node sets 'intent'
    3. If 'db': generate_sql_node sets 'sql_query'
    4. athena_query_node sets 'query_results'
    5. chart_config_node sets 'chart_config'
    6. If 'chat': general_chat_node responds directly
    """
    # Core conversation
    messages: Annotated[List[BaseMessage], add_messages]
    
    # Query classification
    intent: Optional[Literal['db', 'chat']]
    
    # SQL generation
    sql_query: Optional[str]
    
    # Athena results
    query_results: Optional[QueryResults]
    
    # Visualization config
    chart_config: Optional[ChartConfig]
    
    # Metadata (optional)
    error: Optional[str]  # Track errors
    timestamp: Optional[str]  # Track when state was updated

def create_error_state(error_message: str, base_state: ChatState) -> ChatState:
    """
    Helper to create error state while preserving conversation history.
    """
    return {
        **base_state,
        'error': error_message,
        'timestamp': datetime.now().isoformat(),
        'query_results': None,
        'chart_config': None
    }

def serialize_state(state: ChatState) -> Dict[str, Any]:
    """
    Serialize state for storage in checkpointer.
    Handles non-serializable objects.
    """
    serialized = {}
    
    for key, value in state.items():
        if key == 'messages':
            # Messages are handled by LangGraph
            serialized[key] = value
        elif value is None:
            serialized[key] = None
        elif isinstance(value, (str, int, float, bool)):
            serialized[key] = value
        elif isinstance(value, (dict, list)):
            serialized[key] = value
        else:
            # Convert complex objects to string
            serialized[key] = str(value)
    
    return serialized